apiVersion: eksctl.io/vlalpha5
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: myprojectcluster
  labels: 
     app: myweb

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: myweb

  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - name: myweb
        image: dharshan1007/myweb:tagname
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
