apiVersion: apps/v1
kind: deployment
metadata:
  name: demo-deployment
  labels:
    app: newapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newapp
  template:
    metadata:
      labels:
        app: newapp
    spec:
      containers:
      - name: newapp
        image: dharshan1007/myweb:0.0.2
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  selector:
    app: newapp
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30008
  type: LoadBalancer
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: demo-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: newapp
