 # docker-compose.yaml
  version: '3.8'
  services:
    web:
      image: dharshan1007/myweb:0.0.2
      privileged: true
      user: root
      ports:
       - 8090:8080
     container_name: jenkins
    volumes:
      - /home/${myname}/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
